### ISSUE TITLE
I cant import glb file into blender Error:Extension PIXIV_texture_basis is not available on this addon version

### ISSUE THREAD

**Issue by Be3up** [CetaceanNation/misc-scripts#3]
![image](https://github.com/user-attachments/assets/62164ecf-f620-4bd9-9bc9-a1684c218fc9)
I used ur script for downloading vroid models
but i wanna import into blender but Error:Extension PIXIV_texture_basis is not available on this addon version
what do?
if what I want to delete the texture and make my own texture, so can you make a version of the script without the texture?

**Comment by CetaceanNation** [comment]
I do not currently use the models I download with this script, but you can reference [this gist comment](https://gist.github.com/Pldare/ebf704c752a8d77ff9603d4adfe54083?permalink_comment_id=4421921#gistcomment-4421921) for how you might approach this. I don't have the knowledge to assist you any further than a web search on this topic, sorry.

**Comment by Be3up** [comment]
u can make script for downloading models without texture?
i need just model
i wanna custom texture for model
plz make script
